spring:
  config:
    activate:
      on-profile: shardingsphere
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-jdbc.yml?placeholder-type=environment

xincoupon:
  sharding:
    enabled: true
    mode: SHARDINGSPHERE
