spring:
  application:
    name: xin-coupon
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8080

logging:
  level:
    com.xinjia.coupon: info
